/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qHjb9L6DF9J
 */
import Link from "next/link";
import StatefulImg from "@/app/assets/Stateful.png";
import StatefulNextImg from "@/app/assets/Stateful-Next.png";
import StatelessImg from "@/app/assets/Stateless.png";
import ShortLivedImg from "@/app/assets/Short-Lived.png";
import Image from "next/image";

export function EdgeDemoC() {
  return (
    <>
      <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
        Auth at the Edge
      </h2>
      <div className="w-full max-w-5xl mx-auto grid grid-cols-2 gap-4">
        <Image alt="Illustration 1" src={StatefulImg} />
        <Image alt="Illustration 1" src={StatefulNextImg} />
        <Image alt="Illustration 1" src={StatelessImg} />
        <Image alt="Illustration 1" src={ShortLivedImg} />
      </div>
    </>
  );
}
