/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OidVxI2UsQG
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function LandingPageC() {
  return (
    <>
      <section className="text-center mb-8">
        <h2 className="text-4xl font-extrabold text-gray-900 dark:text-white">
          Auth Starts Here
        </h2>
        <p className="mt-4 text-lg text-gray-500 dark:text-gray-300">
          Modern authentication and user management with Next.js and Clerk
        </p>
        <Link href={"/demos"}>
          <Button className="mt-6 py-3 px-6 bg-blue-500 text-white rounded-lg hover:bg-blue-600">
            Get Started
          </Button>
        </Link>
      </section>
      <section className="mt-8">
        <h2 className="text-2xl font-extrabold text-center text-gray-900 dark:text-white">
          Features
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6">
          <div className="text-center">
            <svg
              className=" h-8 w-8 mx-auto text-blue-500 dark:text-blue-300"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10" />
              <path d="m9 12 2 2 4-4" />
            </svg>
            <h3 className="mt-2 text-lg font-semibold text-gray-900 dark:text-white">
              Secure Authentication
            </h3>
            <p className="mt-2 text-gray-500 dark:text-gray-300">
              Best in class security and compliance
            </p>
          </div>
          <div className="text-center">
            <svg
              className=" h-8 w-8 mx-auto text-blue-500 dark:text-blue-300"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <polyline points="16 18 22 12 16 6" />
              <polyline points="8 6 2 12 8 18" />
            </svg>
            <h3 className="mt-2 text-lg font-semibold text-gray-900 dark:text-white">
              Built for Next.js
            </h3>
            <p className="mt-2 text-gray-500 dark:text-gray-300">
              Full advantage of Web APIs and Edge
            </p>
          </div>
          <div className="text-center">
            <svg
              className=" h-8 w-8 mx-auto text-blue-500 dark:text-blue-300"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="12" cy="12" r="10" />
              <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
              <path d="M12 17h.01" />
            </svg>
            <h3 className="mt-2 text-lg font-semibold text-gray-900 dark:text-white">
              Exceptional DX
            </h3>
            <p className="mt-2 text-gray-500 dark:text-gray-300">
              Seamless Integration, Pre-built Components
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
