/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BmA17xcq02o
 */

import type { OrganizationMembership } from "@clerk/nextjs/server";

export function OrgsDemoC(props: { members: OrganizationMembership[] }) {
  return (
    <>
      <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
        Organization Members
      </h2>
      <ul className="w-full max-w-4xl mx-auto grid grid-cols-1 gap-4">
        {props.members.map((membership) => (
          <li className="flex flex-col items-start bg-white rounded-xl shadow-md overflow-hidden dark:bg-gray-800 p-4">
            <div className="flex space-x-4">
              <img
                alt="Profile Picture"
                className="rounded-full"
                height="64"
                src={membership.publicUserData?.imageUrl || "/placeholder.svg"}
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width="64"
              />
              <p className="text-lg font-semibold text-gray-700 dark:text-gray-300 mt-4">
                {membership.publicUserData?.firstName}{" "}
                {membership.publicUserData?.lastName} ({membership.role})
              </p>
            </div>
          </li>
        ))}
      </ul>
    </>
  );
}

export function NoOrg() {
  return (
    <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
      No Organization Selected
    </h2>
  );
}
