/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OglgtaTfCg3
 */

export function ShouldBePrivatePage() {
  return (
    <section className="text-center">
      <h2 className="text-4xl font-extrabold text-gray-900 dark:text-white">
        Private Page
      </h2>
      <p className="mt-4 text-lg text-gray-500 dark:text-gray-300">
        This page needs to be private!
      </p>
    </section>
  );
}
